language: objective-c
osx_image: xcode6.4
before_install:
  - brew update
  - brew install carthage
script: script/cibuild
branches:
  only:
    - master
env:
  global:
    secure: BYlnWyn9lin9b9JbcgpQXFVR6xcjKZ1fITKAxo5XFlPpCwfoz6A10Pkj6kC5+o5Pcf7/wJ0I6xD9pCP7jL+yz9Ny+Okxx8cUhuW/wAL08a8yLi1fKpLe41MEqBz4VUKDhkeFYTL/cpzHIS0oLmuCKJkd+Hddlhx8Y9TyxXNinn17g05Z3ZFbp0pcRPd9Zce+KI1emQv8CprBs0OGeCek468BlBsYdbSZ3lPX1zspg9LP9MezsQunFoJ2Aqksuhq3BNt8AspdPH8WPMhgAomwQeIjpByz6UHyNYQtb+PUqewIWql7PzsoKVQJE9N4uGyIW5374USsSCJHs6o2GSfu1H4Gaoy4z5a0mOZcz+VhuvRnmbxFJDw4x61aTXFIH9y3S2MD1BESNyt07+Lej/40Z+mv+NykaOPOWbY7SYPKs/0aDGtwBUUNFCM086ZSZSOQhhMr4SpNx6zm+tkC2ZRYZL0TZrjZa42Q42mQBB4i0WGZyulpHvVxGjc9htNU3u+OTMjyScWunNZI023gs0y7mpegd5IuAaqMmNUrVjLpIyJVLOZ8nBAX91OQOUnclb7KWrTtYYSmBAsyI6MP0Z/6ZXLVfcQPI3xgVpInEqaTnsFlRTPx16xVpjQRoK13JaM0gQlx3sty+wR6o3b2TkIwQMgPxCb3mS6jH17QJ4xZN14=
